# Generated by Django 6.0.4 on 2026-04-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='chunk_overlap',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='documento',
            name='chunk_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='documento',
            name='chunk_strategy',
            field=models.CharField(default='recursive', max_length=50),
        ),
    ]
