# Generated by Django 6.0.4 on 2026-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documento_chunk_overlap_documento_chunk_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='chunks_sample',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='metadata_sample',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
