# Generated by Django 6.0.4 on 2026-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documento_chunks_sample_documento_metadata_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='qdrant_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='qdrant_synced',
            field=models.BooleanField(default=False),
        ),
    ]
