# Generated by Django 6.0.4 on 2026-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documento_qdrant_sync_date_documento_qdrant_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='qdrant_collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
